name: taxi_kg
description: "Developed by Inane."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  # app_links: ^3.5.0
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  # tuple_dart: ^1.4.2
  riverpod_annotation:
  dio: ^5.4.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator:
flutter:

  uses-material-design: true

  fonts:
    - family: 'MiSans'
      fonts: 
        - asset: assets/fonts/MiSansLatin-Regular.ttf

  assets:
    - assets/images/icons/